## **Arewa Data Science Academy**
### Deep Learning Cohort 2.0
### Name: Ibrahim Manasseh
### Email: mannienokson@gmail.com
### Title: Week 1 Solution
### Exercises Solution

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [2]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [5]:
# Import torch
import torch

# Create random tensor
random_tensor = torch.rand(size = (7,7))
random_tensor,random_tensor.shape

(tensor([[0.8355, 0.7054, 0.2953, 0.6342, 0.5655, 0.9110, 0.1684],
         [0.0654, 0.9542, 0.5217, 0.9872, 0.1379, 0.7723, 0.7837],
         [0.5616, 0.1472, 0.6841, 0.0114, 0.8939, 0.9753, 0.6169],
         [0.4957, 0.2339, 0.8485, 0.1279, 0.2590, 0.4703, 0.5603],
         [0.1490, 0.6165, 0.8044, 0.8765, 0.9054, 0.8376, 0.5291],
         [0.5793, 0.4032, 0.4184, 0.0870, 0.0682, 0.9172, 0.1330],
         [0.4482, 0.4026, 0.9015, 0.3195, 0.6703, 0.6462, 0.5751]]),
 torch.Size([7, 7]))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [13]:
# Create another random tensor
tensor2 = torch.rand(1,7)

# Perform matrix multiplication
torch.mm(random_tensor, tensor2.T)

tensor([[2.2523],
        [2.0423],
        [1.9714],
        [1.3458],
        [2.3081],
        [1.4762],
        [1.9077]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [25]:
# Set manual seed
torch.manual_seed(0)


# Create two random tensors
a = torch.rand(7,7)
b = torch.rand(1,7)

# Matrix multiply tensors
result = torch.mm(a,b.T)
result, result.shape


# Matrix multiply tensors



(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [47]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [35]:
# Set random seed
torch.manual_seed(1234)


# Check for access to GPU
device = 'cuda' if torch.cuda.is_available() else 'cpu'

# Create two random tensors on GPU
x = torch.rand(2,3).to(device)
y = torch.rand(2,3).to(device)

print(f'x = {x}\n\ny = {y}')


x = tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')

y = tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [26]:
# Perform matmul on tensor_A and tensor_B
result = x@y.transpose(0,1)
result, result.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [30]:
# Find max
max = result.max()

# Find min
min = result.min()
print(f'Max = {max}\nMin = {min}')


Max = 0.5617256760597229
Min = 0.3647301495075226


### 9. Find the maximum and minimum index values of the output of 7.

In [37]:
# Find arg max
max_index = result.argmax()

# Find arg min
min_index = result.argmin()

#Output
print(f'Max index = {max_index}\nMin index = {min_index}')

Max index = 3
Min index = 0



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [45]:
# Set seed
torch.manual_seed(7)


# Create random tensor
random_tensor = torch.rand(1,1,1,10)

# Remove single dimensions
squeezed_tensor = random_tensor.squeeze()


# Print out tensors and their shapes
print(random_tensor, random_tensor.shape)
print(squeezed_tensor, squeezed_tensor.shape)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
